# Generated by Django 2.1.5 on 2019-02-12 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('version', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.date.today, help_text="Leave blank if the release date isn't know yet, typically if you're creating the final release just after the alpha because you want to build docs for the upcoming version.", null=True, verbose_name='Release date')),
                ('eol_date', models.DateField(blank=True, help_text="Leave blank if the end of life date isn't known yet, typically because it depends on the release date of a later version.", null=True, verbose_name='End of life date')),
                ('major', models.PositiveSmallIntegerField(editable=False)),
                ('minor', models.PositiveSmallIntegerField(editable=False)),
                ('micro', models.PositiveSmallIntegerField(editable=False)),
                ('status', models.CharField(choices=[('a', 'alpha'), ('b', 'beta'), ('c', 'release candidate'), ('f', 'final')], editable=False, max_length=1)),
                ('iteration', models.PositiveSmallIntegerField(editable=False)),
                ('is_lts', models.BooleanField(default=False, verbose_name='Long term support release')),
            ],
        ),
    ]
