# Generated by Django 6.0 on 2026-01-20 14:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0005_release_artifacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="Leave blank if the release date isn't known yet, typically if you're creating the final release just after the alpha because you want to build docs for the upcoming version.",
                null=True,
                verbose_name="Release date",
            ),
        ),
    ]
