# Generated by Django 6.1 on 2026-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0006_alter_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="is_lts",
            field=models.BooleanField(
                default=False,
                help_text='Is this a release for an <abbr title="Long Term Support">LTS</abbr> Django version (e.g. 5.2a1, 5.2, 5.2.4)? Always set for calendar versions, which are all supported for three years.',
                verbose_name="Long Term Support",
            ),
        ),
    ]
