os: linux
dist: bionic
language: python

python:
  - "3.8"

services: postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
  - PGPORT=5433

install:
  - pip install coveralls tox

before_script:
  - psql -c 'CREATE USER "djangoproject" WITH CREATEDB SUPERUSER;' -U travis
  - psql -c 'CREATE DATABASE "djangoproject" OWNER "djangoproject";' -U travis
  - psql -c 'CREATE USER "code.djangoproject" WITH CREATEDB SUPERUSER;' -U travis
  - psql -c 'CREATE DATABASE "code.djangoproject" OWNER "code.djangoproject";' -U travis
  - psql -U travis -d code.djangoproject < tracdb/trac.sql

script:
  - tox

after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.net#django-websites"
    on_success: always
    on_failure: always
    use_notice: true
