# Generated by Django 2.1.7 on 2019-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_format', models.CharField(choices=[('reST', 'reStructuredText'), ('html', 'Raw HTML')], max_length=50)),
                ('body', models.TextField()),
                ('slug', models.SlugField(unique_for_date='date')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Board Minutes',
                'ordering': ['-date'],
                'get_latest_by': 'id',
            },
        ),
    ]
