# Generated by Django 2.2.24 on 2021-06-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAwardCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for the group being inducted, e.g. 'Q1 2021'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cohort_date', models.DateField(help_text='Date this cohort was approved by the DSF Board')),
            ],
        ),
        migrations.CreateModel(
            name='CoreAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text="Recipient's name", max_length=1023, unique=True)),
                ('link', models.URLField(blank=True, help_text='Optional link for this recipient', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional one-paragraph description/bio of why this person received the award')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='foundation.CoreAwardCohort')),
            ],
            options={
                'ordering': ['recipient'],
            },
        ),
    ]
