# Generated by Django 5.1.5 on 2025-05-19 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_hardcode_currency_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
