# Generated by Django 5.1.5 on 2025-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_hardcode_currency_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='body',
            field=models.TextField(help_text="Supports reStructuredText. See <a href='https://www.djangoproject.com/styleguide/content/'>supported formatting</a>."),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='board_attendees',
            field=models.ManyToManyField(help_text='Make sure to choose the correct year', related_name='meetings_attended', to='foundation.boardmember'),
        ),
    ]
