# Generated by Django 5.2 on 2025-09-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_boardmember_account_protect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedcorporatemember',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='approvedgrant',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='approvedindividualmember',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='account',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='office',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='term',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='board_attendees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='business',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='non_board_attendees',
        ),
        migrations.DeleteModel(
            name='ActionItem',
        ),
        migrations.DeleteModel(
            name='ApprovedCorporateMember',
        ),
        migrations.DeleteModel(
            name='ApprovedGrant',
        ),
        migrations.DeleteModel(
            name='ApprovedIndividualMember',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='BoardMember',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='NonBoardAttendee',
        ),
    ]
