# Generated by Django 5.2 on 2025-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_boardmember_account_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='next_meeting_date',
            field=models.DateField(blank=True, help_text="This will be shown on the website as the board's next meeting date. The latest meeting's Next Meeting Date will be used.", null=True),
        ),
    ]
