# Generated by Django 5.2 on 2025-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_boardmember_account_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='next_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
