# Generated by Django 6.0.3 on 2026-04-13 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0007_boardmember_account_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Optional banner body text. HTML is supported and will be rendered as given.",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for the call-to-action button. Both label and URL must be provided for the button to appear.",
                        max_length=100,
                        verbose_name="Call-to-action button label",
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for the call-to-action button. Both label and URL must be provided for the button to appear.",
                        verbose_name="Call-to-action button URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one banner can be active at a time. Activating this banner will deactivate all others.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
