<?xml version="1.0"?>
<!-- RSS generated by Trac v<?cs var:$trac.version ?> on <?cs var:$trac.time ?> -->
<rss version="2.0">
   <?cs set base_url = $HTTP.Protocol+'://'+$HTTP.Host ?>
   <?cs if $HTTP.Port ?>
     <?cs set base_url = $base_url + ':' + $HTTP.Port ?>
   <?cs /if ?>
    <channel>
      <?cs if $project.name.encoded ?>
        <title><?cs var:$project.name.encoded ?>: Revisions of <?cs var:$log.path ?></title>
      <?cs else ?>
        <title>Revisions of <?cs var:$log.filename ?></title>
      <?cs /if ?>
      <link><?cs var:$base_url ?><?cs var:$log.href ?></link>
      <description>Trac Log - Revisions of <?cs var:$log.path ?></description>
      <language>en-us</language>
      <generator>Trac v<?cs var:$trac.version ?></generator>
      <?cs each:item = $log.items ?>
       <item>
<!--  XXX: author element requires email address in rss 2.0.
           maybe we should use the DC rdf stuff for metadata instead?
       <author><?cs var:$item.author ?></author> -->
         <pubDate><?cs var:$item.gmt ?></pubDate>
         <title><?cs var:$item.rev+': '+$item.shortlog ?></title>
         <link><?cs var:$base_url+$item.file_href ?></link>
         <description><?cs var:$item.log.raw ?></description>
         <category>Report</category>
       </item>
      <?cs /each ?>
    </channel>
</rss>
