<?xml version="1.0"?>
<!-- RSS generated by Trac v<?cs var:trac.version ?> on <?cs var:trac.time ?> -->
<rss version="2.0">
 <channel><?cs 
  if:project.name_encoded ?>
   <title><?cs var:project.name_encoded ?>: Ticket <?cs var:title ?></title><?cs 
  else ?>
   <title>Ticket <?cs var:title ?></title><?cs 
  /if ?>
  <link><?cs var:base_host ?><?cs var:ticket.href ?></link>
  <description><?cs var:ticket.description.formatted ?></description>
  <language>en-us</language>
  <generator>Trac v<?cs var:trac.version ?></generator><?cs 
  each:change = ticket.changes ?>
   <item><?cs
    if:change.author ?><author><?cs var:change.author ?></author><?cs
    /if ?>
    <pubDate><?cs var:change.date ?></pubDate>
    <title><?cs var:change.title ?></title>
    <link><?cs var:base_host ?><?cs var:ticket.href ?></link>
    <description>
    <?cs if:len(change.fields) ?>
    &lt;ul&gt;<?cs
    each:field = change.fields ?>
    &lt;li&gt;&lt;strong&gt;<?cs name:field ?>&lt;/strong&gt; <?cs
     if:!field.old ?>set to &lt;em&gt;<?cs
      var:field.new ?>&lt;/em&gt;<?cs
     elif:field.new ?>changed from &lt;em&gt;<?cs var:field.old
      ?>&lt;/em&gt; to &lt;em&gt;<?cs
      var:field.new ?>&lt;/em&gt;.<?cs
     else ?>deleted<?cs
     /if ?>&lt;/li&gt;<?cs
    /each ?>
    &lt;/ul&gt;
    <?cs /if ?>
    <?cs var:change.comment ?>
    </description>
    <category>Ticket</category>
   </item><?cs 
  /each ?>
 </channel>
</rss>
