# Generated by Django 2.1.5 on 2019-02-12 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('feed_url', models.URLField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=500)),
                ('approval_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Denied'), ('A', 'Approved')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('date_modified', models.DateTimeField()),
                ('guid', models.CharField(db_index=True, max_length=500, unique=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.Feed')),
            ],
            options={
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('can_self_add', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.FeedType'),
        ),
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
