# Generated by Django 3.2.19 on 2023-06-05 03:45

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_increase_url_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDjangoCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=125)),
                ('city', models.CharField(max_length=85)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica')], max_length=15)),
                ('website_url', models.URLField(blank=True, default=None, max_length=250, null=True)),
                ('event_site_url', models.URLField(blank=True, default=None, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='localdjangocommunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_site_url__isnull', False), ('website_url__isnull', False)), models.Q(('event_site_url__isnull', False), ('website_url__isnull', True)), models.Q(('event_site_url__isnull', True), ('website_url__isnull', False)), _connector='OR'), name='website_url_and_or_event_site_url'),
        ),
    ]
