# Generated by Django 5.0.9 on 2024-11-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_feeditem_add_index_date_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localdjangocommunity',
            options={'verbose_name_plural': 'Local Django Communities'},
        ),
    ]
