# Generated by Django 5.2.7 on 2025-10-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trac_username",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=150
            ),
        ),
    ]
