# Generated by Django 5.2.7 on 2026-10-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_trac_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="trac_username",
        ),
        migrations.CreateModel(
            name="TracAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="<p>⚠️ The username on Trac. <b>Setting this verifies ownership.</b></p><p>While a Trac account can be linked to multiple users, once claimed, any user with a matching <code>djangoproject.com</code> username who lacks their own verified Trac account will no longer be able to display Trac stats on their profile.</p>",
                        max_length=150,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "username")},
            },
        ),
    ]
