# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_squashed_0005_remove_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrelease',
            name='lang',
            field=models.CharField(choices=settings.LANGUAGES, default='en', max_length=7),
        ),
    ]
