# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20171107_1513'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['release', 'title'], name='document_release_title_idx'),
        ),
    ]
