# Generated by Django 5.2 on 2025-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_document_metadata_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrelease',
            name='support_end',
            field=models.DateField(blank=True, help_text='The end of support for this release of Django.', null=True),
        ),
    ]
