# Generated by Django 2.1.5 on 2019-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique_for_date='pub_date')),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this entry live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive entries whereas the general public aren't.")),
                ('pub_date', models.DateTimeField(help_text='For an entry to be published, it must be active and its publication date must be in the past.', verbose_name='Publication date')),
                ('content_format', models.CharField(choices=[('reST', 'reStructuredText'), ('html', 'Raw HTML')], max_length=50)),
                ('summary', models.TextField()),
                ('summary_html', models.TextField()),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'get_latest_by': 'pub_date',
                'ordering': ('-pub_date',),
                'db_table': 'blog_entries',
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('external_url', models.URLField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this event live (see also the publication date). Note that administrators (like yourself) are allowed to preview inactive events whereas the general public aren't.")),
                ('pub_date', models.DateTimeField(help_text='For an event to be published, it must be active and its publication date must be in the past.', verbose_name='Publication date')),
            ],
            options={
                'ordering': ('-pub_date',),
                'get_latest_by': 'pub_date',
            },
        ),
    ]
