# Generated by Django 4.2.14 on 2024-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("reST", "reStructuredText"),
                    ("html", "Raw HTML"),
                    ("md", "Markdown"),
                ],
                max_length=50,
            ),
        ),
    ]
