# Generated by Django 5.1.5 on 2025-03-27 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_content_format_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Not published anywhere, just used internally', max_length=100)),
                ('image', models.FileField(upload_to='blog/images/%Y/%m/')),
                ('alt_text', models.TextField(help_text='Make the extra effort, it makes a difference 💖')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_on',),
            },
        ),
    ]
