# Generated by Django 5.2 on 2025-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_entry_social_media_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_searchable',
            field=models.BooleanField(help_text='Tick to make this entry allow this entry to appear in the Django documentation search.', null=True),
        ),
    ]
