# Generated by Django 5.2 on 2025-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_entry_social_media_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_searchable",
            field=models.BooleanField(
                default=False,
                help_text="Tick to make this entry appear in the Django documentation search.",
            ),
        ),
    ]
