# Generated by Django 5.2.7 on 2026-02-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_entry_is_searchable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="is_searchable",
        ),
    ]
