# Generated by Django 5.2 on 2025-07-24 07:22

from django.db import migrations


def set_is_searchable(apps, schema_editor):
    Entry = apps.get_model("blog", "Entry")
    # If this is large, this should be split into batched updates
    Entry.objects.filter(is_searchable__isnull=True).update(is_searchable=False)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_entry_is_searchable'),
    ]

    operations = [
        migrations.RunPython(set_is_searchable, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
