# Generated by Django 6.1 on 2026-09-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_entry_is_searchable"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="automatic_post_to_socials",
            field=models.BooleanField(
                default=True,
                help_text="Please uncheck this if you want a custom social media post for this entry or you do not want this entry posted to socials.",
            ),
        ),
    ]
