# Generated by Django 6.1 on 2026-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_entry_is_searchable"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Have the entry fixed at the top of the page."
            ),
        ),
    ]
