# Generated by Django 5.2 on 2025-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_set_is_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_searchable',
            field=models.BooleanField(default=False, help_text='Tick to make this entry appear in the Django documentation search.'),
        ),
    ]
