# Generated by Django 6.0 on 2026-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_entry_is_searchable"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_searchable",
            field=models.BooleanField(
                default=False,
                help_text="Tick to make this entry appear in the Django documentation search.",
            ),
        ),
    ]
