# Generated by Django 2.1.5 on 2019-02-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('django_id', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('id', models.TextField()),
                ('filename', models.TextField()),
                ('size', models.IntegerField()),
                ('_time', models.BigIntegerField(db_column='time')),
                ('description', models.TextField()),
                ('author', models.TextField()),
                ('ipnr', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'attachment_django_view',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('owner', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('_due', models.BigIntegerField(db_column='_due')),
                ('_completed', models.BigIntegerField(db_column='_completed')),
            ],
            options={
                'managed': False,
                'db_table': 'milestone',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('repos', models.IntegerField()),
                ('rev', models.TextField(primary_key=True, serialize=False)),
                ('_time', models.BigIntegerField(db_column='time')),
                ('author', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'revision',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('_time', models.BigIntegerField(db_column='time')),
                ('_changetime', models.BigIntegerField(db_column='changetime')),
                ('severity', models.TextField()),
                ('owner', models.TextField()),
                ('reporter', models.TextField()),
                ('cc', models.TextField()),
                ('priority', models.TextField()),
                ('status', models.TextField()),
                ('resolution', models.TextField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('_time', models.BigIntegerField(db_column='time')),
            ],
            options={
                'managed': False,
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('django_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.IntegerField()),
                ('_time', models.BigIntegerField(db_column='time')),
                ('author', models.TextField()),
                ('ipnr', models.TextField()),
                ('text', models.TextField()),
                ('comment', models.TextField()),
                ('readonly', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'wiki_django_view',
            },
        ),
        migrations.CreateModel(
            name='TicketChange',
            fields=[
                ('ticket', models.ForeignKey(db_column='ticket', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='changes', serialize=False, to='tracdb.Ticket')),
                ('author', models.TextField()),
                ('field', models.TextField()),
                ('oldvalue', models.TextField()),
                ('newvalue', models.TextField()),
                ('_time', models.BigIntegerField(db_column='time')),
            ],
            options={
                'managed': False,
                'ordering': ['_time'],
                'db_table': 'ticket_change',
            },
        ),
        migrations.CreateModel(
            name='TicketCustom',
            fields=[
                ('ticket', models.ForeignKey(db_column='ticket', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='custom_fields', serialize=False, to='tracdb.Ticket')),
                ('name', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'ticket_custom',
            },
        ),
    ]
