# Generated by Django 3.2.23 on 2024-02-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attachment",
            table="attachment",
        ),
        migrations.AlterModelTable(
            name="wiki",
            table="wiki",
        ),
    ]
