# Generated by Django 6.0.3 on 2026-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0002_alter_securityissue_blogdescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Markdown format. Single `backticks` for inline code. Copy from release notes, include severity sentence.",
                ),
                verbose_name="Blog description",
            ),
        ),
    ]
