# Generated by Django 6.0.4 on 2026-04-15 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_alter_securityissue_blogdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="cvss_v3_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Base score (0.0-10.0) from the CVSS v3.1 calculator.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="CVSS v3.1 Score",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="cvss_v3_vector_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CVSS v3.1 vector string. Example: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                max_length=256,
                verbose_name="CVSS v3.1 Vector String",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="cvss_v4_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Base score (0.0-10.0) from the CVSS v4.0 calculator.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="CVSS v4.0 Score",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="cvss_v4_vector_string",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CVSS v4.0 vector string. Example: CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N",
                max_length=256,
                verbose_name="CVSS v4.0 Vector String",
            ),
        ),
    ]
