# Generated by Django 6.0.4 on 2026-04-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0005_populate_cvss_v4_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securityissue",
            name="attack_complexity",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="attack_requirements",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="attack_vector",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="automatable",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="cvss_base_score",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="privileges_required",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="provider_urgency",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="recovery",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="safety",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="sub_availability_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="sub_confidentiality_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="sub_integrity_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="user_interaction",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="value_density",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="vuln_availability_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="vuln_confidentiality_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="vuln_integrity_impact",
        ),
        migrations.RemoveField(
            model_name="securityissue",
            name="vulnerability_response_effort",
        ),
    ]
