# Generated by Django 6.0.4 on 2026-05-07 02:32

import django.core.validators
from django.db import migrations, models

import checklists.models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0006_remove_securityissue_attack_complexity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="cve_year_number",
            field=models.CharField(
                default=checklists.models.get_cve_default,
                max_length=1024,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="CVE-\\d{4}-\\d{4,5}")
                ],
                verbose_name="CVE ID",
            ),
        ),
    ]
