# Generated by Django 6.0.5 on 2026-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0007_alter_securityissue_cve_year_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="discovery",
            field=models.CharField(
                choices=[
                    ("EXTERNAL", "External"),
                    ("INTERNAL", "Internal"),
                    ("USER", "During use"),
                    ("UPSTREAM", "Upstream"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="EXTERNAL",
                max_length=128,
            ),
        ),
    ]
