# Generated by Django 6.0.5 on 2026-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0008_securityissue_discovery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityissue",
            name="blogdescription",
            field=models.TextField(
                blank=True,
                help_text="Markdown format. Single `backticks` for inline code. Copy from release notes, include severity sentence.",
                verbose_name="Blog description",
            ),
        ),
    ]
