# Generated by Django 6.0.6 on 2026-07-17 08:08

from django.db import migrations, models

import checklists.models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0009_alter_securityissue_blogdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="unsupported_series",
            field=models.CharField(
                blank=True,
                default=checklists.models.get_unsupported_series_default,
                help_text='Comma separated versions (such as "5.0.x, 4.1.x, and 3.2.x") used in the CVE description noting that earlier, unsupported Django series were not evaluated and may also be affected. Leave blank to omit that sentence entirely.',
                max_length=1024,
                verbose_name="Unsupported series note",
            ),
        ),
    ]
