# Generated by Django 6.1 on 2026-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0011_releaser_user_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityissue",
            name="analyst",
            field=models.CharField(
                blank=True,
                help_text='Optional. Comma separated list of names, one per person analyzing the issue (triage, severity and CVSS scoring). Each name gets its own "analyst" entry in the CVE credits. Leave blank to omit these credits, or when the analysis was done by the release coordinator.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="reviewer",
            field=models.CharField(
                blank=True,
                help_text='Optional. Comma separated list of names, one per person reviewing the fix. Each name gets its own "remediation reviewer" entry in the CVE credits. Leave blank to omit these credits.',
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="remediator",
            field=models.CharField(
                blank=True,
                help_text='Comma separated list of names, one per person developing the fix. Each name gets its own "remediation developer" entry in the CVE credits.',
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="securityissue",
            name="reporter",
            field=models.CharField(
                blank=True,
                help_text='Comma separated list of names, one per person reporting the issue. Each name gets its own "reporter" entry in the CVE credits.',
                max_length=1024,
            ),
        ),
    ]
