# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_squashed_0004_corporatemember_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatemember',
            name='django_usage',
            field=models.TextField(blank=True, help_text='Not displayed publicly.', verbose_name='How does your organization use Django'),
        ),
    ]
