# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_individual_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatemember',
            name='inactive',
            field=models.BooleanField(default=False, help_text='No longer renewing.'),
        ),
    ]
