# Generated by Django 2.1.2 on 2018-10-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20170216_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='individualmember',
            name='website',
        ),
    ]
