# Generated by Django 3.2.25 on 2024-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20181001_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmember',
            name='reason_for_leaving',
            field=models.TextField(blank=True, help_text='⚠️ This reason is publicly displayed on the website. <strong>Do not include confidential details.</strong>'),
        ),
    ]
