# Generated by Django 5.0.9 on 2024-11-16 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_individualmember_add_reason_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreviousTeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Use for details such as term dates. This is publicly displayed within brackets next to the members name. <strong>Do not include confidential details.</strong>')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.individualmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='former_members',
            field=models.ManyToManyField(related_name='teams_former_member', through='members.PreviousTeamMembership', to='members.individualmember'),
        ),
    ]
