# Generated by Django 6.1 on 2026-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_alter_individualmember_add_reason_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporatemember",
            name="membership_level",
            field=models.IntegerField(
                choices=[
                    (1, "Bronze"),
                    (2, "Silver"),
                    (3, "Gold"),
                    (4, "Platinum"),
                    (5, "Diamond"),
                    (6, "Sponsored Fellow"),
                ]
            ),
        ),
    ]
