# Generated by Django 5.2.7 on 2025-10-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_individualmember_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individualmember",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "send_account_invite_mail",
                        "Can send account invite mail to an individual member",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="individualmember",
            name="account_invite_mail_sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="individualmember",
            name="member_until",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
