# Generated by Django 5.2.7 on 2025-10-21 23:53

from django.conf import settings
from django.db import migrations, transaction


def link_individual_members_to_users_by_email(apps, schema_editor):
    # These models aren't the ones imported from the `models.py` files.
    # They're fake, and constructed based on the historical migrations.
    # Ensure that the `Migration.dependencies` contains the migrations needed to
    # construct the models that are used here.
    IndividualMember = apps.get_model("members.IndividualMember")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    individual_members_queryset = IndividualMember.objects.filter(
        user_id__isnull=True,
    ).select_for_update(
        nowait=False,
    )
    users_queryset = User.objects.filter(
        email__in=individual_members_queryset.values_list("email", flat=True),
    )
    for user in users_queryset.iterator():
        with transaction.atomic():
            IndividualMember.objects.filter(email=user.email).update(user=user)


def noop(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0011_alter_individualmember_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            link_individual_members_to_users_by_email,
            # Don't raise `django.db.migrations.exceptions.IrreversibleError`
            # when reverting to an older migration.
            reverse_code=noop,
        ),
    ]
