---
name: Tests on Django main

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    run:
        uses: ./.github/workflows/tests-base.yml
        with:
            django-version: "Django @ git+https://github.com/django/django.git@main"
        secrets:
            codecov-token: ${{ secrets.CODECOV_TOKEN }}
