name: prek checks

on:
    pull_request:
    push:
        branches: [main]

jobs:
    prek:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5.0.0
            - uses: j178/prek-action@v1.0.11
