---
name: Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    run:
        uses: ./.github/workflows/tests-base.yml
        secrets:
            codecov-token: ${{ secrets.CODECOV_TOKEN }}
